#!/bin/sh
set -eu

export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/xdg-runtime}"
export WLR_BACKENDS="${WLR_BACKENDS:-headless}"
export WLR_RENDERER="${WLR_RENDERER:-pixman}"
export WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-wayland-1}"

install -d -m 700 -o 1000 -g 1000 "$XDG_RUNTIME_DIR"

dbus-daemon --session --nofork --address="unix:path=$XDG_RUNTIME_DIR/bus" &

/usr/bin/sway "$@" &
sway_pid=$!

while [ ! -S "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" ]; do
	if ! kill -0 "$sway_pid" 2>/dev/null; then
		wait "$sway_pid" || true
		exit 1
	fi
	sleep 1
done

wayvnc 127.0.0.1 5901 &

/usr/share/novnc/utils/novnc_proxy --listen 6080 --vnc 127.0.0.1:5901 &

wait "$sway_pid"